version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    privileged: true
    user: root
    ports:
      - ${JENKINS_PORT}:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ${DOCKER_HOME}/jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker